version: '3.8'

services:
  backend:
    build: ./src/backend/japroject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/backend/japroject:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./src/frontend
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    command: npm start